### ISSUE TITLE
Add Commands for NEC Projector P401W

### ISSUE THREAD

**Issue by ssharpe83713** [LightsOnHudson/FPP-Plugin-Projector-Control#13]
Please add the commands for this projector to the plugin.  I have attached that manual which contains the details on page 215.  Thanks!
[NEC Projector Manual.pdf](https://github.com/LightsOnHudson/FPP-Plugin-Projector-Control/files/11691879/NEC.Projector.Manual.pdf)

**Comment by patdelaney** [comment]
I added it to the FalconCHristmass FPP Projector Plugin Repo. Plese uninstall the one you have and reinstall.  What version of FPP are running.

**Comment by ssharpe83713** [comment]
Thanks, Pat. I'm still on a version of 4... works for my needs.
