### ISSUE TITLE
Plugin Not Installing on FPP 8.1

### ISSUE THREAD

**Issue by wbhartmanii** [LightsOnHudson/FPP-Plugin-Projector-Control#19]
Plugin does not appear to install. 
Command not found in fpp_install.sh:10

> Version Info |  
> FPP Version: | 8.1
> Platform: | Raspberry Pi (Pi 4)
> FPP OS Build: | v2024-09
> OS Version: | Raspbian GNU/Linux 12 (bookworm)
> Hardware Serial Number: | 100000005113ee82
> Kernel Version: | 6.6.47-v7l+
> System Boot Time: | 2024-10-11 15:50:20
> fppd Uptime: | 07:27
> Local Git Version: | e444786
> FPP Mode: | Remote

**Install log:**
```
Fri Oct 11 03:53:09 PM BST 2024
Installing plugin FPP-Plugin-Projector-Control
Cloning into 'FPP-Plugin-Projector-Control'...
Running fpp_install.sh script for FPP-Plugin-Projector-Control
~/media/plugins/FPP-Plugin-Projector-Control ~/media/plugins

“The plugin is checking for the required library.”


“This can take a couple minutes.”

Loading internal logger. Log::Log4perl recommended for better logging
Reading '/home/fpp/.cpan/Metadata'
  Database was generated on Fri, 11 Oct 2024 13:41:01 GMT
Net::PJLink is up to date (1.03).
/home/fpp/media/plugins/FPP-Plugin-Projector-Control/fpp_install.sh: line 10: setSetting: command not found
~/media/plugins
```

**Comment by patdelaney** [comment]
I just installed it and it appears ok

**Comment by patdelaney** [comment]
This is the wrong Repo for reporting Bugs. It has been ported to falcon chesitmas. I'm not sure How you got to this link?

**Comment by wbhartmanii** [comment]
shrug? I clicked on 'Report a Bug' in the plugin screen and this is where it took me. It's now taking me to the other repo.
I also just tried reinstalling and it's working now. That may be why it wasn't installing before....plugin was pointed at the wrong repo.
Anyway, odd, seems fine now.

**Comment by patdelaney** [comment]
I'm glad it's working for you.
