### ISSUE TITLE
How to add new "projector" types to the plugin to use in FPP

### ISSUE THREAD

**Issue by Jchuchla** [LightsOnHudson/FPP-Plugin-Projector-Control#2]
what's the process to get another model added to the code?  I'm using Samsung monitors in my display and while they're not projectors, this plugin will work just fine to control them so long as I can get the commands added.  So do I just send them to someone, or do I fork, make the additions and then push the commit?  if it's the latter, how do I get the updates propagated to my FPP?

**Comment by LightsOnHudson** [comment]
Send me the codes through the FPP PM or here. and we will get them added. need the baud rate, or ip information, etc. how are you going to use samsung monitors? just curious.

**Comment by Jchuchla** [comment]
I have the codes from the book, but I want to verify them before sending them to you. I seem to remember from the last time I coded for these was that there was something weird with the address byte description in the protocol doc.  I'll test them later tonight after my show is finally running.    These monitors are actually a pull-out from  emergency operations center upgrade I did a few years back.  I actually did the control system programming for the system they were part of, so I know I have the working control strings in the archives if the ones in the book end up being wrong.

 

I'm using them in my show for digital signage.  Specifically my tune to sign, which will be more of a now playing sign that also carries various announcements and such.

 

 

--Jon Chuchla--

 

Email: jon@chuchla.com

Mobile: 708-280-6744

**Comment by Jchuchla** [comment]
Here's what I came up with.  I copied all of the input sources from the protocol document for the sake of completeness.  but I marked the ones that aren't available on the unit I have.  I'm sure the other input commands will work on monitors with those inputs available.  They're consistent with the ones that do work and were in the document.  The lines with no comment tested good on my unit.  I think you can just copy and paste the below section into the inc file.  though not being familiar with pi coding, I'm not sure if the comments and formatting is correctly formated for the language.

 

Thanks!

 

//Samsung MDC Protocol (Multi Display Control)

//Tested on 320MP-2

 

//the checksum is the sum of all values except for the header. If, as shown in the example below (11 + FF + 01 +01 =112), the sum is a three-digit interger, discard rhe first digit and keep the lower two.

 

                              Array("NAME" => "Samsung Commercial Flat Panel (MDC)",

                                                            //Power

                                                            "ON"     => "\xAA\x11\xFE\x01\x01\x11",

                                                            "OFF"    => "\xAA\x11\xFE\x01\x00\x10",

                                                            //Inputs

                                                            "SVIDEO"             => "\xAA\x14\xFE\x01\x04\x17",//not available on test tv

                                                            "VIDEO"               => "\xAA\x14\xFE\x01\x0C\x1F",

                                                            "YPbPr"                => "\xAA\x14\xFE\x01\x08\x1B",

                                                            "PC"                      => "\xAA\x14\xFE\x01\x14\x27",

                                                            "DVIVid"              => "\xAA\x14\xFE\x01\x1F\x32",

                                                            "PC1"                    => "\xAA\x14\xFE\x01\x15\x28",//not available on test tv

                                                            "PC2"    => "\xAA\x14\xFE\x01\x16\x29",//not available on test tv

                                                            "DVID"                 => "\xAA\x14\xFE\x01\x18\x2B",

                                                            "BNC"                   => "\xAA\x14\xFE\x01\x1E\x31",

                                                            "MagicNet"         => "\xAA\x14\xFE\x01\x20\x33",//not available on test tv

                                                            "HDMI"                => "\xAA\x14\xFE\x01\x21\x34",

                                                            "ATV"                   => "\xAA\x14\xFE\x01\x30\x43",//not available on test tv

                                                            "DTV"                   => "\xAA\x14\xFE\x01\x40\x53",//not available on test tv

 

                                                            "BAUD_RATE" => "9600",

                                                            "CHAR_BITS" => "8",

                                                            "STOP_BITS" => "1",

                                                            "PARITY" => "none"

                              ),

 

 

--Jon Chuchla--

 

Email: jon@chuchla.com

Mobile: 708-280-6744

**Comment by Jchuchla** [comment]
BTW, which USB-serial adapters are people using with this that are known to work well with the Pi?  Just figure I'd ask before going thru the pi driver guessing game.

 

--Jon Chuchla--

**Comment by LightsOnHudson** [comment]
I have a trendnet. generic white cable -molded end usb. they are about 6-9$ on amazon. i have 2-3 of them on my projector and another one to control my HDMI switcher.

**Comment by LightsOnHudson** [comment]
Ok, this has been added. we have to use _ intead of spaces on the names. please click the UpdatePluginn button in the plugin for the projector and then leave the plugin and then go back in and you should see it in there. just select it, and select the USB port it is on. save, leave the plugin, go back into the plugin, and verify it stuck and then you should be good to go, and there should be some events/scripts that are created for you to schedule within your playlist...

**Comment by Jchuchla** [comment]
I saw that one on Amazon. I'll pick one up. Thanks. 

--Jon Chuchla--

**Comment by Jchuchla** [comment]
I think I messed things up. When I updated and changed to the new display type, I only saw a few scripts added and I still had scripts left over from whatever model was previously selected. (I knew this from the input names) So since it wasn't obvious for some scripts which were from the new model and which were old, I decided to delete al the scripts and was going to start over.  But even when I switch to a different model and switch back it's not generating them again.  I even tried deleting the plugin and  reinstalling it but it still didn't add them. What can I do to get them back? And only the ones from the model I need. 

--Jon Chuchla--

**Comment by LightsOnHudson** [comment]
Hi Jon,
It should be doing it correctly when you at least install the plugin and
select the one you want.

..delete the plugin
..delete the events
..install the plugin
..visit the plugin page and UPDATE the plugin first
..Leave the plugin page.
..view the plugin page, select your configuration and click SAVE
..leave the plugin
..go back into the plugin.

then to to the Event page and see if they are re-created there.

**Comment by Jchuchla** [comment]
When you say event page, do you mean scripts? I don't remember ever seeing an event page in fpp. 
Also when you say delete the plugin, is that the uninstall from the plugin repo page? Or some other manual process?
Does it matter that I haven't yet selected a com port while testing? (Still Waiting on my Amazon order) I wouldn't think so because it created the scripts the first time around.

--Jon Chuchla--

**Comment by LightsOnHudson** [comment]
Correct. you do not need to define the serial port yet.
Deleting  = uninstall the plugin
Event page = It is in the Status menu. towards the bottom. It should have
in there the various events for you.
And yes, the scripts would be there too

**Comment by Jchuchla** [comment]
That's what I missed, the events page.  As soon as I deleted the events in there and then went back to the plugin page and hit save, it then recreated all the scripts and events. 

 

Question.  do I need the events there for the plugin to work?  For my application, I planned on just hitting the scripts manually via HTTP request.  I guess I can leave them, they're not in the way.  It's just my OCD.  Ironically, I'm not using FPP for anything other than playing video and controlling the display. Admittedly, this is an odd application, but I just want to learn the limits so I know what I can do with it. 

 

 

--Jon Chuchla--

 

Email: jon@chuchla.com

Mobile: 708-280-6744

**Comment by patdelaney** [comment]
This is old
