### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by garfatc** [LightsOnHudson/FPP-Plugin-Projector-Control#8]
I'm all new to this, I'm trying to control my projector [EIKI LC-SXG400](https://www.eiki.com/item/lc-sxg400lc-sxg400l-no-lens/) via serial to tun it off and on, my projector is not on the list so I was wondering if anyone could help me to add it to the list. [PDF to Serial Commands](https://www.eiki.com/download/eiki/eiki-rs-232-serial-commands/LC-SXG400%20RS-232%20basic%20serial%20commands.pdf) Thanks!

**Comment by patdelaney** [comment]
I believe that if you select the Sanyo_PLC_HP7000L  that is the same set of commands. Please test that on.

**Comment by patdelaney** [comment]
Did you test it out?

**Comment by garfatc** [comment]
> Did you test it out?

Yes, I did, it did not work. I'm thinking that the pinout for the projector is different iv used the same cable on different projects and it works, still trying to figure it out. il keep you updated, thanks for your help!

**Comment by patdelaney** [comment]
I think the pinout is in that document you sent me.

Pat

**Comment by garfatc** [comment]
Hi Pat, after reviewing the pinout of the cable I notice that It did not line up with what was given in the pdf. I made up a new cable and it worked, I thought it was a standard thing. Thanks for your time!

**Comment by patdelaney** [comment]
Thats good to here, to confirm did you use the Sanyo_PLC_HP7000L setting?  If so I will update the plugin with that

**Comment by garfatc** [comment]
Yes, I did, I only use the on and immediate off functions.
