### ISSUE TITLE
Possible to add Promethan Projector PRM-45

### ISSUE THREAD

**Issue by tyger95** [LightsOnHudson/FPP-Plugin-Projector-Control#9]
I have a request to add the Promethan Projecotr PRM-45 as one of the projector on the FPP Plugin.  Is there any possibility that it can be done.  I have attached the codes to this message.   Thank You!
[Projector Settings UST-P1-and-PRM-45-RS232-Codes.pdf](https://github.com/LightsOnHudson/FPP-Plugin-Projector-Control/files/6298125/Projector.Settings.UST-P1-and-PRM-45-RS232-Codes.pdf)
.

**Comment by patdelaney** [comment]
I'll take a look tonight

**Comment by tyger95** [comment]
THANK YOU SO MUCH!

**Comment by patdelaney** [comment]
I added the projector to both Repositories. For now because I don't have the projector to test, I just added basic on/off commands. Update the plugin and try it out. If you have issues, we can meet in the zoom room.

**Comment by tyger95** [comment]
Thanks, I will test in the next few days.

**Comment by tyger95** [comment]
I was able to test the scripts and the On and Off commands both work.  Thanks for the work you have done so far!

**Comment by patdelaney** [comment]
ok thanks for the update.
